import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export enum PermissionType {
  DIRECTORY = 1,
  MENU = 2,
  BUTTON = 3,
  API = 4,
}

export const permissionsSeed = [
  {
    parentId: null,
    name: 'System',
    code: null,
    type: PermissionType.DIRECTORY,
    title: 'System Management',
    icon: 'SettingOutlined',
    path: '/system',
    component: 'Layout',
    redirect: '/system/permission',
    visible: true,
    keepAlive: false,
    description: 'System management',
    sort: 1,
    status: 1,
  },
  {
    parentId: 1,
    name: 'PermissionManage',
    code: 'permission:list',
    type: PermissionType.MENU,
    title: 'Permission Management',
    icon: 'SafetyOutlined',
    path: '/system/permission',
    component: '/system/permission/index',
    redirect: null,
    visible: true,
    keepAlive: true,
    description: 'Manage permissions dynamically',
    sort: 1,
    status: 1,
  },
  {
    parentId: 2,
    name: 'PermissionCreate',
    code: 'permission:create',
    type: PermissionType.BUTTON,
    title: 'Create Permission',
    icon: null,
    path: null,
    component: null,
    redirect: null,
    visible: false,
    keepAlive: false,
    description: 'Create new permission',
    sort: 1,
    status: 1,
  },
  {
    parentId: 2,
    name: 'PermissionUpdate',
    code: 'permission:update',
    type: PermissionType.BUTTON,
    title: 'Update Permission',
    icon: null,
    path: null,
    component: null,
    redirect: null,
    visible: false,
    keepAlive: false,
    description: 'Update permission',
    sort: 2,
    status: 1,
  },
  {
    parentId: 2,
    name: 'PermissionDelete',
    code: 'permission:delete',
    type: PermissionType.BUTTON,
    title: 'Delete Permission',
    icon: null,
    path: null,
    component: null,
    redirect: null,
    visible: false,
    keepAlive: false,
    description: 'Delete permission',
    sort: 3,
    status: 1,
  },
  {
    parentId: 2,
    name: 'PermissionTree',
    code: 'permission:tree',
    type: PermissionType.BUTTON,
    title: 'View Permission Tree',
    icon: null,
    path: null,
    component: null,
    redirect: null,
    visible: false,
    keepAlive: false,
    description: 'Get permission tree',
    sort: 4,
    status: 1,
  },
  {
    parentId: 1,
    name: 'RoleManage',
    code: 'role:list',
    type: PermissionType.MENU,
    title: 'Role Management',
    icon: 'TeamOutlined',
    path: '/system/role',
    component: '/system/role/index',
    redirect: null,
    visible: true,
    keepAlive: true,
    description: 'Manage roles',
    sort: 2,
    status: 1,
  },
  {
    parentId: 6,
    name: 'RoleCreate',
    code: 'role:create',
    type: PermissionType.BUTTON,
    title: 'Create Role',
    icon: null,
    path: null,
    component: null,
    redirect: null,
    visible: false,
    keepAlive: false,
    description: 'Create new role',
    sort: 1,
    status: 1,
  },
  {
    parentId: 6,
    name: 'RoleUpdate',
    code: 'role:update',
    type: PermissionType.BUTTON,
    title: 'Update Role',
    icon: null,
    path: null,
    component: null,
    redirect: null,
    visible: false,
    keepAlive: false,
    description: 'Update role',
    sort: 2,
    status: 1,
  },
  {
    parentId: 6,
    name: 'RoleDelete',
    code: 'role:delete',
    type: PermissionType.BUTTON,
    title: 'Delete Role',
    icon: null,
    path: null,
    component: null,
    redirect: null,
    visible: false,
    keepAlive: false,
    description: 'Delete role',
    sort: 3,
    status: 1,
  },
  {
    parentId: 6,
    name: 'RoleAssignPermissions',
    code: 'role:assign-permissions',
    type: PermissionType.BUTTON,
    title: 'Assign Permissions',
    icon: null,
    path: null,
    component: null,
    redirect: null,
    visible: false,
    keepAlive: false,
    description: 'Assign permissions to role',
    sort: 4,
    status: 1,
  },
];

export async function seedPermissions() {
  console.log('🌱 Initializing permissions...');

  try {
    const result = await prisma.permission.createMany({
      data: permissionsSeed,
      skipDuplicates: true,
    });

    console.log(`✅ Successfully initialized ${result.count} core permissions`);
    console.log('   Including: Permission Management, Role Management');
    console.log('');
    console.log('💡 Add other permissions dynamically via:');
    console.log('   1. POST /api/permissions');
    console.log('   2. Admin interface');
    console.log('');
  } catch (error) {
    console.error('❌ Failed to initialize permissions:', error);
    throw error;
  }
}
